[variables]
NIXPACKS_PUPPETEER = '1'
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'

[phases.setup]
aptPkgs = ['chromium-browser', 'wget', 'gnupg', 'ca-certificates', 'libnss3-dev', 'libgdk-pixbuf2.0-dev', 'libgtk-3-dev', 'libxss-dev', 'libasound2', 'fonts-liberation', 'libatk1.0-0', 'libatk-bridge2.0-0', 'libcups2', 'libdrm2', 'libgbm1', 'libnspr4', 'libxcomposite1', 'libxdamage1', 'libxfixes3', 'libxrandr2', 'xdg-utils']
